Repository liferay/liferay-ckeditor, pull requests merged in 2019-05, with the labels that each got.

#20 chore: apply shellcheck fixes to ck.sh
  ck.sh
Labels: chore

#23 doc: tweak README for accuracy
  README.md
Labels: documentation

#24 fix: make ck.sh behavior match README
  ck.sh
Labels: bug

#25 fix: broken "ck.sh build"
  ck.sh
Labels: bug

#26 fix: work around different Git behavior across versions
  ck.sh
Labels: bug

#27 fix: tabs in popups overflowing in CKEditor with "maximize" plugin (LPS-95472)
  patches/0001-patch-LPS-89596-Changed-position-of-drag-icon-for-IE.patch
  patches/0002-LPS-95472-Use-width-inherit-instead-of-width-100-to-.patch
Labels: bug
